# GitHub Actions Workflow Configuration
# This file contains shared configuration for all workflows

# Environment variables that should be consistent across all workflows
defaults:
  env:
    NODE_VERSION: "20"
    NX_CLOUD_DISTRIBUTED_EXECUTION: "false"
    CI: true
    NODE_ENV: "production"

# Common step configurations
common_steps:
  checkout:
    uses: actions/checkout@v4
  
  setup_node:
    uses: actions/setup-node@v4
    with:
      node-version: "20"
      cache: "npm"
  
  install_deps:
    run: npm ci --prefer-offline --no-audit
  
  cache_nx:
    uses: actions/cache@v4
    with:
      path: .nx/cache
      key: nx-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
      restore-keys: |
        nx-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-
